# Generated by Django 3.1.3 on 2023-12-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20231217_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.instructor')),
            ],
        ),
    ]
