# Generated by Django 3.1.3 on 2023-12-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_courseinstructors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseInstructors',
            new_name='CourseInstructor',
        ),
    ]
