# Generated by Django 3.1.3 on 2023-12-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20231217_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.choice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.submission')),
            ],
        ),
    ]
